_emsch_go_to:
    config:
        path: '/_emsch/go-to/{_locale}/{contentType}/{ouuid}'
        requirements: { ouuid: \S+ }
        defaults: { _format: json }
        controller: 'emsch.controller.router::redirect'
    template_static: template/redirects/_emsch_go_to.json.twig
_emsch_template_preview_loader:
    config:
        path: '/_emsch/templates/{iframeId}'
        method: [GET]
    template_static: template_ems/channel/page-component-preview-loader.html.twig
_emsch_template_preview:
    config:
        path: '/_emsch/templates/{iframeId}'
        method: [POST]
    template_static: template_ems/channel/page-component-preview.html.twig
robots.txt:
    config:
        path: robots.txt
        defaults: { _format: txt }
    template_static: template/seo/robots.txt.twig
favicon.ico:
    config:
        path: favicon.ico
        controller: 'emsch.controller.router::redirect'
    template_static: template/redirects/favicon.json.twig
apple-touch-icon.png:
    config:
        path: apple-touch-icon.png
        controller: 'emsch.controller.router::redirect'
    template_static: template/redirects/apple-touch-icon.json.twig
icon.png:
    config:
        path: '{name}-{width}x{height}.png'
        controller: 'emsch.controller.router::redirect'
        requirements: { name: android-chrome|favicon|mstile, width: 16|32|70|144|150|310|192|512, height: 16|32|70|144|150|310|192|512 }
    template_static: template/redirects/icon.json.twig
emsch_manifest:
    config:
        path: /site.webmanifest
        defaults: { _format: txt }
    template_static: template/favicon/site.webmanifest.twig
emsch_browserconfig:
    config:
        path: /browserconfig.xml
        defaults: { _format: xml }
    template_static: template/favicon/browserconfig.xml.twig
sitemap.xml:
    config:
        path: sitemap.xml
        defaults: { _format: xml }
        requirements: {  }
    template_static: template/seo/sitemap.xml.twig
google_verification:
    config:
        path: google559a317bdba2ec40.html
    template_static: template/seo/google.html.twig
emsch_login:
    config:
        controller: emsch.controller.security.login
        path: /login
        method: [POST, GET]
    template_static: template/security/login.html.twig
emsch_profile:
    config:
        path: /profile
        defaults: { _authenticated: true }
    template_static: template/security/profile.html.twig
emsch_api_form_attachment:
    config:
        path: '/form/{submissionId}/attachment/{submissionFileId}'
        defaults: { apiName: backend, _authenticated: true }
        controller: 'emsch.controller.api::getSubmissionFile'
        requirements: { submissionId: '.*', submissionFileId: '.*' }
emsch_slideshow:
    config:
        path: { en: 'slideshow/{slug}', fr: 'fr/presentation/{slug}' }
    query: '{"query":{"bool":{"must":[{"term":{"%_locale%.show":true}},{"term":{"%_locale%.slug":"%slug%"}},{"terms":{"_contenttype":["slideshow"]}}]}},"size":1}'
    template_static: template/slideshow/revealjs.html.twig
emsch_page:
    config:
        path: { en: 'page/{slug}', fr: 'fr/page/{slug}' }
    query: '{"query":{"bool":{"must":[{"term":{"%_locale%.show":true}},{"term":{"%_locale%.slug":"%slug%"}},{"terms":{"_contenttype":["page"]}}]}},"size":1}'
    template_static: template/page/by_type.html.twig
    template_source: '[template]'
emsch_missing_translation:
    config:
        path: '/{_locale}/missing/{contentType}/{ouuid}'
        requirements: { _locale: en|fr|nl|de }
    query: '{"query":{"bool":{"must":[{"term":{"_contenttype":{"value":"%contentType%"}}},{"term":{"_id":{"value":"%ouuid%"}}}]}},"size":1}'
    template_static: template/base/missing_translation.html.twig
site.webmanifest:
    config:
        path: site.webmanifest
        defaults: { _format: json }
    template_static: template/head/site.webmanifest.twig
emsch_language_selection:
    config:
        path: /
    template_static: template/view/language_select.html.twig
emsch_word_export:
    config:
        path: '/_word_export/{contentType}/{ouuid}.docx'
        requirements: { path: '^(?!(fr/|nl/|de/|_wdt/|_profiler/|file/)(.*$)?).+', _locale: en|fr|nl|de }
    query: '{"query":{"bool":{"should":[{"bool":{"must":[{"terms":{"_contenttype":["%contentType%"]}},{"term":{"_id":"%ouuid%"}}]}},{"bool":{"must":[{"nested":{"path":"paths","query":{"term":{"paths.target":{"value":"%contentType%:%ouuid%","boost":3}}}}},{"nested":{"path":"paths","query":{"term":{"paths.locale":{"value":"%_locale%"}}}}},{"terms":{"_contenttype":["structure"]}}]}}]}},"size":1}'
    template_static: template/page/word-export/document.html.twig
emsch_media_file:
    config:
        path: '/media-files{path}'
        requirements: { path: .+ }
        controller: 'emsch.controller.router::redirect'
    query: '{"query":{"bool":{"must":[{"terms":{"_contenttype":["media_file"]}},{"terms":{"media_path":["%path%"]}}]}},"size":1,"_source":{"excludes":["media_file._content","media_file._language","media_file._author","media_file._title","media_file._date"],"includes":["media_file.*","after","before","username","password","disposition"]}}'
    template_static: template/redirects/media_files.json.twig
emsch_news_details:
    config:
        path: { fr: '/fr/news/{year}-{month}-{day}/{slug}', nl: '/nl/news/{year}-{month}-{day}/{slug}' }
    query: '{"query":{"bool":{"must":[{"terms":{"_contenttype":["news"]}},{"terms":{"%locale%.slug":["%slug%"]}}]}},"size":1}'
    template_static: template/news/details.html.twig
emsch_path:
    config:
        path: { fr: '/fr/{path}', nl: '/nl/{path}' }
        requirements: { path: '^(?!(fr/|nl/|de/|_wdt/|_profiler/|_error/|metric|file|logout/saml|oauth/)(.*$)?).+' }
        defaults: { path: home }
    query: '{"query":{"bool":{"must":[{"nested":{"path":"paths","query":{"term":{"paths.path":"%path%"}}}},{"nested":{"path":"paths","query":{"term":{"paths.locale":"%_locale%"}}}},{"terms":{"_contenttype":["section"]}}]}},"size":1}'
    template_static: template/structure/by_path.html.twig
emsch_error:
    config:
        path: '/_error/{statusCode}'
        controller: 'emsch.controller.router::errorPreview'
        defaults: { statusCode: 500 }
